//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfClubMVCApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GolfClubEntities : DbContext
    {
        public GolfClubEntities()
            : base("name=GolfClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_club> tbl_club { get; set; }
        public virtual DbSet<tbl_Members> tbl_Members { get; set; }
    
        public virtual int sp_delete_member(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_member", memberIDParameter);
        }
    
        public virtual int sp_insert_members(ObjectParameter memberID, string memberName, string gender, string membershipType, Nullable<int> clubID)
        {
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var membershipTypeParameter = membershipType != null ?
                new ObjectParameter("MembershipType", membershipType) :
                new ObjectParameter("MembershipType", typeof(string));
    
            var clubIDParameter = clubID.HasValue ?
                new ObjectParameter("ClubID", clubID) :
                new ObjectParameter("ClubID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_members", memberID, memberNameParameter, genderParameter, membershipTypeParameter, clubIDParameter);
        }
    
        public virtual int sp_update_members(Nullable<int> memberID, string memberName, string gender, string membershipType, Nullable<int> clubID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var membershipTypeParameter = membershipType != null ?
                new ObjectParameter("MembershipType", membershipType) :
                new ObjectParameter("MembershipType", typeof(string));
    
            var clubIDParameter = clubID.HasValue ?
                new ObjectParameter("ClubID", clubID) :
                new ObjectParameter("ClubID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_members", memberIDParameter, memberNameParameter, genderParameter, membershipTypeParameter, clubIDParameter);
        }
    
        public virtual ObjectResult<sp_view_members_Result> sp_view_members()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_members_Result>("sp_view_members");
        }
    }
}
