//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfClubMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Members
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string Gender { get; set; }
        public string MembershipType { get; set; }
        public Nullable<int> ClubID { get; set; }
    
        public virtual tbl_club tbl_club { get; set; }
    }
}
